// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Jo9-HkaIf8C5quaPhCDrK61DHKcmrqs',
    appId: '1:119533557094:web:67c81c3acd248208e4e4a7',
    messagingSenderId: '119533557094',
    projectId: 'solid-daylight-332812',
    authDomain: 'solid-daylight-332812.firebaseapp.com',
    databaseURL: 'https://solid-daylight-332812-default-rtdb.firebaseio.com',
    storageBucket: 'solid-daylight-332812.appspot.com',
    measurementId: 'G-5Y74NYMCRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbW66-DxbNmgadWHFsU_j-uv04a6RXQR0',
    appId: '1:119533557094:android:c10cab5cd96b1811e4e4a7',
    messagingSenderId: '119533557094',
    projectId: 'solid-daylight-332812',
    databaseURL: 'https://solid-daylight-332812-default-rtdb.firebaseio.com',
    storageBucket: 'solid-daylight-332812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMslXIUvUIT-MKaAbBJVsYFGX2QEO8AM',
    appId: '1:119533557094:ios:7ee134e4e5f4ec6ee4e4a7',
    messagingSenderId: '119533557094',
    projectId: 'solid-daylight-332812',
    databaseURL: 'https://solid-daylight-332812-default-rtdb.firebaseio.com',
    storageBucket: 'solid-daylight-332812.appspot.com',
    iosClientId: '119533557094-mshhdg7cq63t6hnisuog8rmitefr79gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mof',
  );
}
